### ISSUE TITLE
build_context and building of tests

### ISSUE THREAD

**Issue by hannesm** [dbuenzli/topkg#79] opened 2016-10-25 13:21 UTC
When I use an opam repository which contains development packages (their url is not a tarball, but a vcs repository), topkg treats them as ``Dev build_context`, thus tests are enabled.  But opam does not, thus the test dependencies are not installed.

A workaround is to extend the `build:` instructions in the `opam` file with `--tests false`,
This is slightly inconvenient, I wonder whether the detection magic can cope better with this scenario.

Occurences where this happened is e.g. https://github.com/mirage/mirage-dev/commit/3618326ac00eabeac69f6beeb81c772c5779b71f and https://github.com/mirage/mirage-dev/pull/177/commits/270323e3aae3a2bc02fba76f42796b7e1c60f314 (travis failure if `--tests false` is not present https://travis-ci.org/mirage/mirage-dev/jobs/170403318)

**Comment by avsm** [comment] 2016-10-27 20:44
Ah yes, I've been adding `--tests false` everywhere in my uses of `build`

**Comment by hannesm** [comment] 2016-10-29 14:06
maybe related is that installing something from an opam repository which uses a git url (such as mirage-dev) does not apply appropriate watermarking... `mirage` installed from the mirage-dev repo claims `mirage --version` to be `%%VERSION%%`.  I saw build errors (on OpenBSD) when modifying the opam file to include `"--pinned" "true"` (saying that the source is not under version control).

**Comment by pqwy** [comment] 2016-10-29 17:02
The problem is that Opam's ability to have a package URL that's pointing to a git repo defeats Opam's `pinned` variable, insofar as it denotes a build from the project directory, as opposed to a distribution-ready archive.

If you actually pin a package, `topkg` can see the VCS and is informed about `--pinned %{pinned}%`, so it infers the [`Pin` context](http://erratique.ch/software/topkg/doc/Topkg.Conf.html#VALbuild_context).

But if the opam file points to a git URL, `pinned` is not set, yet the VCS is still present, so `topkg` infers a development working dir. This enables tests and skips watermarking.

The presence of both pins and git URLs gives the `pinned` variable the following meaning: "Either we are fixed to a particular version, or we are in this special situation, which can otherwise arise in a completely different way." It essentially means that the user chose to diverge from the package repository, but it's *not* indicative of whether Opam is building the package straight from the project directory.

IMHO ideally Opam should set `pinned` for packages with git URLs, because this is exactly the same scenario as git-pinning. That's unless there is another way for it to inform the build system that the package is either pinned or otherwise pulled from a VCS. Unfortunately, I can't find one.

The alternative is potentially fragile second-guessing by `topkg`, which is bound to create more problems.

@AltGr What do you say? Is there way to classify these scenarios together from the opam file?

**Comment by dbuenzli** [comment] 2016-10-30 14:54
There was a discussion that was never ended about this here https://github.com/mirage/functoria/issues/67. I think like @pqwy that packages with git-urls should be considered as `pinned` since AFAIU they are observationally equivalent to git pins. I also think that adding more magic is not the right solution. Please report the issue to `opam`.

**Comment by dbuenzli** [comment] 2017-02-28 09:46
> Ah yes, I've been adding --tests false everywhere in my uses of build

This is not a good idea since hopefully `opam` v2 gives us a `%{test}%` variable which will allow to avoid repeating ourselves between `build:` and `build-test:`. 

Apparently nobody took care to report this upstream so if anyone testing `opam v2` could confirm to me that: 

1. `%{pinned}%` is still `false` on packages with `git` url. In which case I will report this upstream since people are not interested in helping. 
2. That the `%{test}%` variable is now available.

**Comment by AltGr** [comment] 2017-02-28 13:10
Hope this will be satisfying, here is where opam 2 stands:
- `%{pinned}%` is `true` only on pinned packages; there is another variable `%{dev}%` that tells whether the package is bound to a version-controlled URL.
- `%{test}%` is indeed available, and is `true` when building with `--test` AND the package is listed on the command-line.

**Comment by AltGr** [comment] 2017-02-28 13:11
(it would be worth reporting the lack of documentation though)

**Comment by dbuenzli** [comment] 2017-02-28 13:39
> %{pinned}% is true only on pinned packages; there is another variable %{dev}% that tells whether the package is bound to a version-controlled URL.

Thanks. Just to make sure `%{dev}%` also `true` on `git`-pinned packages.

**Comment by dbuenzli** [comment] 2017-02-28 14:21
@AltGr, if the answer to latter question is true this will be *very* statisfying. 

However I need to change my own [broken and stupid terminology](http://erratique.ch/software/topkg/doc/Topkg.Conf.html#VALbuild_context). Here's a plan: 

1. Deprecate the `--pinned` option and [configuration key](http://erratique.ch/software/topkg/doc/Topkg.Conf.html#VALpinned) (which deprecated `--installer`... I hope I will eventually get this right) and equate it with a new configuration key `Conf.dev_pkg` baked by a `--dev-pkg` option in which we'll plug the `%{dev}%` variable.
2. Change the `Pin` case of [`build_context` ](http://erratique.ch/software/topkg/doc/Topkg.Conf.html#TYPEbuild_context) currently inferred when `Conf.vcs && Conf.pinned` holds to `Dev_distrib` which will be inferred when `Conf.vcs && Conf.pkg_dev` holds.

If someone has a better name than `Dev_distrib` for 2. it's welcome. I also wonder how much breakage this might entail, if too much I may aswell keep the misnamed `Pin` case.

**Comment by dbuenzli** [comment] 2017-02-28 14:34
A bit unsure about 2. even the [sample code](file:///Users/dbuenzli/.opam/4.03.0/var/cache/odig/odoc/topkg/Topkg/index.html#config_store) matches on `build_context`.

**Comment by AltGr** [comment] 2017-02-28 15:00
(yes, git-pinned packages have `dev = true`)

**Comment by dbuenzli** [comment] 2017-02-28 20:25
@AltGr one clarification about the semantics of `dev` (whose answer would be good to add to the docs). Does `dev = true` imply that the build directory is VCS managed, i.e. the functionality of the VCS is available to the build system.

**Comment by dbuenzli** [comment] 2017-02-28 20:58
@AltGr is it really `%{test}%` ? [This](https://github.com/ocaml/opam/issues/2277) seems to indicate that that it is `%{build-test)%`, also is there a `run-test:` field now ? The docs are silent about it.

**Comment by AltGr** [comment] 2017-03-14 10:27
Ah, sorry for the lag, got distracted while checking and responding.

- The _depends variables_ are `build`, `test`, `doc`, `dev` ; these can be used in dependencies (`depends: "foo" {test}`)

- The _commands variables_ are `build-test`, `build-doc` ; these can be used in commands (`build: [ [make] [make "tests"] {test} ]` ; or `["./configure" "--enable-tests" {test}]`). These need documenting yet.

The reason for the different name is that `doc` is already used throughout as the name of the doc directory.

- The `build-test:` _field_ still exists unchanged at the moment. It may be deprecated or removed, but could actually still be useful as a `run-test` feature. Should it be renamed ?

So in the current state, it should be preferred to filter commands based on the `build-test` variable, but the `build-test:` field is still handled.

**Comment by dbuenzli** [comment] 2017-03-14 11:17
> [ [make] [make "tests"] {test} ] ; or ["./configure" "--enable-tests" {test}])

I think you meant `build-test`.

> The build-test: field still exists unchanged at the moment. It may be deprecated or removed, but could actually still be useful as a run-test feature. Should it be renamed ?

In general it is good if `opam` can make the distinction between building, installing and running things (and this is the reason why the confusing `opam build` command should be renamed asap...). So I'll assume we'll have `run-test` in opam v2.0 :-). 

Thanks for the input.

**Closed by dbuenzli** 2017-03-14 11:17 UTC
Labels: next
